# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Homatics Box R 4K Plus
# https://4pda.to/forum/index.php?showtopic=1080563
# Homatics/SEI804HM/YYJ:14/UKG3.241022.001/4576:user/release-keys

oem: "Homatics"             # The company that made your device (e.g. Samsung)
product: "SEI804HM"         # The product code. May be same as device code or model code.
device: "YYJ"          # The device code. May be same as model code.
android_version: "11" # Only put in the major version number.
build_tag: "RTT0.211009.001"       # Example: RKQ1.211119.001
incremental: "6261"     # Example: 2206131341
model: "Box R 4K Plus"           # The model code. (e.g. SM-T380)
