# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys

oem: "TECNO"             # The company that made your device (e.g. Samsung)
product: "CL8-OP"         # The product code. May be same as device code or model code.
device: "TECNO-CL8"          # The device code. May be same as model code.
android_version: "15" # Only put in the major version number.
build_tag: "AP3A.240905.015.A2"       # Example: RKQ1.211119.001
incremental: "250222V15607"     # Example: 2206131341
model: "TECNO CAMON 30 Pro 5G (Android 15)"           # The model code. (e.g. SM-T380)
