# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys

oem: "TECNO"             # The company that made your device (e.g. Samsung)
product: "LG7n-GL"         # The product code. May be same as device code or model code.
device: "TECNO-LG7n"          # The device code. May be same as model code.
android_version: "12" # Only put in the major version number.
build_tag: "SP1A.210812.016"       # Example: RKQ1.211119.001
incremental: "240816V1799"     # Example: 2206131341
model: "TECNO POVA 4"           # The model code. (e.g. SM-T380)
