# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Nokia Streaming Box 8010
# https://4pda.to/forum/index.php?showtopic=1087773
# Nokia/SEI804NK/YYJ:14/UKG3.241022.001/4576:user/release-keys

oem: "Nokia"             # The company that made your device (e.g. Samsung)
product: "SEI804NK"         # The product code. May be same as device code or model code.
device: "YYJ"          # The device code. May be same as model code.
android_version: "14" # Only put in the major version number.
build_tag: "UKG3.241022.001"       # Example: RKQ1.211119.001
incremental: "4576"     # Example: 2206131341
model: "SEI Robotics Nokia Streaming Box 8010"           # The model code. (e.g. SM-T380)
