name: GH Actions Cron Schedule
on:
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare the environment
      run: |
        pip install -r requirements.txt

    - name: Check ota
      shell: bash
      env:
        bot_token: ${{ secrets.BOT_TOKEN }}
        chat_id: ${{ secrets.CHAT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for file in configs/config-*.yml; do python checkota.py -c $file && echo "//"; done

    - name: Check for updates and create release
      if: success()
      run: |
        bash release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
